FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY bot ./bot
COPY scripts ./scripts

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "bot.main"]
